//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models.Entitys;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace Models.EntityTypeConfiguration
{   
    /// <summary>
    /// 实体-MergePayInfo 
    /// </summary>
	public class MergePayInfoEntityTypeConfiguration :  EntityTypeConfiguration<MergePayInfo>
    {
		public MergePayInfoEntityTypeConfiguration()
		{
			/// <summary>
        /// 
        /// </summary>
        HasKey(s => s.MergeId);
        Property(s=>s.MergeId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.MerchantNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.UserId).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.OrderCount).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Amount).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Name).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.BankCardNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.IdentityCardNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.BankName).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.IdentityType).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Status).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.PayDate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.RepulseRemark).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ImgPath).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.UpdateTime).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.AddTime).IsRequired();
 
			//配置表名称
			ToTable("MergePayInfo");

		}
    }
}
