//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models.Entitys;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace Models.EntityTypeConfiguration
{   
    /// <summary>
    /// 实体-OrderInfo 
    /// </summary>
	public class OrderInfoEntityTypeConfiguration :  EntityTypeConfiguration<OrderInfo>
    {
		public OrderInfoEntityTypeConfiguration()
		{
			/// <summary>
        /// 
        /// </summary>
        HasKey(s => s.OrderId);
        Property(s=>s.OrderId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.OrderNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Category).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.InsurerType).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ProvinceCode).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.CityCode).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.InsurerName).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.OrderSourceOrganization).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.SettlementOrganization).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.OrderSourceDate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.PolicyNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.EndorsementsNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.InsuranceStartDate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ApplicantName).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Insured).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.IsLicence).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.LicenceNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.VehicleFrameNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.EngineNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.DebutDate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.PremiumAmount).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.VehicleAndVesselTaxAmount).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ProcedureFeeRate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ProcedureFeeClearingForm).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.ProcedureFeeClearingFee).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.CommissionRate).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.CommissionClearingForm).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.CommissionClearingFee).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Status).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.AddTime).IsRequired();
 
			//配置表名称
			ToTable("OrderInfo");

		}
    }
}
