//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models.Entitys;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace Models.EntityTypeConfiguration
{   
    /// <summary>
    /// 实体-OrderSettlementAgent 
    /// </summary>
	public class OrderSettlementAgentEntityTypeConfiguration :  EntityTypeConfiguration<OrderSettlementAgent>
    {
		public OrderSettlementAgentEntityTypeConfiguration()
		{
			/// <summary>
        /// 
        /// </summary>
        HasKey(s => s.Id);
        Property(s=>s.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.MerchantNo).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.UserId).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.OrderNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.PolicyNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Name).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.BankCardNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.IdentityCardNo).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.BankName).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Amount).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.IdentityType).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.Status).IsRequired();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.AddTime).IsRequired();
 
			//配置表名称
			ToTable("OrderSettlementAgent");

		}
    }
}
